"""Added table

Revision ID: 421ca7fa47b6
Revises: 63cac121f078
Create Date: 2023-11-08 11:45:50.428701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421ca7fa47b6'
down_revision = '63cac121f078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('trip', sa.Integer(), nullable=False),
    sa.Column('started', sa.DateTime(), nullable=False),
    sa.Column('finished', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip')
    # ### end Alembic commands ###
