"""Added column

Revision ID: 63cac121f078
Revises: 8d54d3028e6e
Create Date: 2023-11-06 09:09:47.455845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63cac121f078'
down_revision = '8d54d3028e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pallet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pallet', schema=None) as batch_op:
        batch_op.drop_column('year')

    # ### end Alembic commands ###
