"""Added unique constraint to trip table

Revision ID: 75ebb8bce2ba
Revises: 421ca7fa47b6
Create Date: 2023-11-08 12:52:11.737292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75ebb8bce2ba'
down_revision = '421ca7fa47b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.alter_column('started',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('finished',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_trip_year'), ['year', 'trip'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_trip_year'), type_='unique')
        batch_op.alter_column('finished',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('started',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
