"""added uq_trip_year_hold_space_layer in pallet model

Revision ID: 8ada504a194e
Revises: 75ebb8bce2ba
Create Date: 2023-11-09 02:31:13.044157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ada504a194e'
down_revision = '75ebb8bce2ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pallet', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_pallet_year'), ['year', 'trip', 'hold', 'space', 'layer'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pallet', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_pallet_year'), type_='unique')

    # ### end Alembic commands ###
