"""Adding tables - create fish, bin, box

Revision ID: 95bebb648a34
Revises: 8ada504a194e
Create Date: 2024-12-09 22:30:18.249969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95bebb648a34'
down_revision = '8ada504a194e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('grader', sa.Integer(), nullable=True),
    sa.Column('fish_weight', sa.Float(), nullable=True),
    sa.Column('bin', sa.Integer(), nullable=True),
    sa.Column('bin_name', sa.String(length=64), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bin'))
    )
    op.create_table('box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('bin', sa.String(length=64), nullable=True),
    sa.Column('product', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_box'))
    )
    op.create_table('fish',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('bin', sa.Integer(), nullable=True),
    sa.Column('product', sa.Integer(), nullable=True),
    sa.Column('ip', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fish'))
    )
    with op.batch_alter_table('fish', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fish_datetime'), ['datetime'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fish', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fish_datetime'))

    op.drop_table('fish')
    op.drop_table('box')
    op.drop_table('bin')
    # ### end Alembic commands ###
