"""Adding Storage table

Revision ID: dc7717611aa3
Revises: 95bebb648a34
Create Date: 2025-01-06 00:40:17.112675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc7717611aa3'
down_revision = '95bebb648a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freezer', sa.Integer(), nullable=True),
    sa.Column('space', sa.Integer(), nullable=True),
    sa.Column('tow', sa.Integer(), nullable=True),
    sa.Column('product', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storage')),
    sa.UniqueConstraint('freezer', 'space', name='unique_freezer_space')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage')
    # ### end Alembic commands ###
